### ISSUE TITLE
Stuck after entering TEAM ID

### ISSUE THREAD

**Issue by jigsaw007** [tavasyaa/fplseasonreview#1]
It doesnt load past after entering TEAM ID .

**Comment by tavasyaa** [comment]
Hey, thanks for the note! It's a CORS issue -- to solve this, clone this repository: https://github.com/Rob--W/cors-anywhere and run it on your computer (npm install and then npm start to run when you're in the directory). Clone the newest version of fplreasonreview and start it, and it should now work. Keep in mind that it takes a long time for the code to run, so wait about 35-40 sec after you hit the submit button (I know this is a long time and will fix it before launch).

Let me know if this works, if it doesn't please go to console and let me know what the issue is!

**Comment by tavasyaa** [comment]
Actually, run the newest version of the app now and ignore the above comment! It should still take 35-40sec though
